### ISSUE TITLE
taggedPDF is not mapping with PDF UA

### ISSUE THREAD

**Issue by gautierchomel** [w3c/a11y-discov-vocab#111]
In my understanding, taggedPDF is a mandatory feature to prove PDF UA compliance. 

Therefore, we can deduce that a PDF that is PDF UA compliant has a tagged PDF feature, but the reverse is not true; a PDF can have a tagged PDF feature without being PDF UA compliant. 

https://github.com/w3c/a11y-discov-vocab/blob/2c64f33aeab54a79a445bb374d25dc0efe1cf304/crosswalk/index.html#L518-L519

Related to discussion at [ONIX display - other values - PDF/ UA - 1 and PDF/ UA- 2 - codes 05 & 06 #322](https://github.com/w3c/publ-a11y/issues/322)

**Comment by mattgarrish** [comment]
Yes, being tagged and conforming to the standard at a specific level are two different things. You can't equate the feature being present to conformance.

**Comment by mattgarrish** [comment]
Noting that we make some clarifications in #119 about taggedPDF needing to meet pdf/ua requirements, but I don't think that changes anything here. If you additionally want to know if a pdf is pdf/ua conformant, you need to get that info from the pdf, or the external metadata would need to carry the info.

I'm going to close this issue as we don't deal with conformance identifiers in the schema.org metadata, but feel free to re-open it if you think there's something we need to consider for the vocabulary.
