### ISSUE TITLE
Trying to access https://www.w3.org/2021/a11y-discov-vocab/latest/ results in 404 error

### ISSUE THREAD

**Issue by Different2day** [w3c/a11y-discov-vocab#117]
Hi, 

I tried to access 
Latest published version of Schema.org Accessibility Properties for Discoverability Vocabulary
**https://www.w3.org/2021/a11y-discov-vocab/latest/**

**from** 

various schema.org pages, e.g. 
- https://schema.org/WebPageElement - accessMode - [approved vocabulary](https://www.w3.org/2021/a11y-discov-vocab/latest/#accessMode-vocabulary)
- https://schema.org/VideoObject - accessModeSufficient - [approved vocabulary](https://www.w3.org/2021/a11y-discov-vocab/latest/#accessModeSufficient-vocabulary)

the latest draft of the document
- https://w3c.github.io/a11y-discov-vocab/ - Latest published version:
https://www.w3.org/2021/a11y-discov-vocab/latest/

and am **getting** this **message**

The latest version of the vocabulary is available at https://www.w3.org/community/reports/a11y-discov-vocab/CG-FINAL-vocabulary-20240906/

followed by this **error message**

https://www.w3.org/community/reports/a11y-discov-vocab/CG-FINAL-vocabulary-20240906/
404
File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL as well as any file permissions.
For root URLs (like http://example.com/) you must provide an index.html file.

[Read the full documentation](https://help.github.com/pages/) for more information about using GitHub Pages.

[GitHub Status](https://githubstatus.com/) — [@githubstatus](https://twitter.com/githubstatus)

Anya Sims

**Comment by mattgarrish** [comment]
Thanks for the report!

@deniak could this be related to the redirect problem that occurred a little while back? It looks like both the published vocabulary and crosswalk have stopped working:

- https://www.w3.org/community/reports/a11y-discov-vocab/CG-FINAL-vocabulary-20240906/
- https://www.w3.org/community/reports/a11y-discov-vocab/CG-FINAL-crosswalk-20240906/

**Comment by deniak** [comment]
Hi @mattgarrish, thanks for the report and sorry for the inconvenience. It was related to a configuration mistake on the [cg-report repository](https://github.com/w3c/cg-reports) that occurred a few days ago. It is now be fixed.

**Comment by mattgarrish** [comment]
Perfect, thanks! Closing this issue.
