### ISSUE TITLE
longDescription clarity needed

### ISSUE THREAD

**Issue by clapierre** [w3c/a11y-discov-vocab#15]
4.2.4.8 longDescription

Descriptions are provided for image-based visual content and/or complex structures such as tables, mathematics, diagrams, and charts.

I think we will need to spell out here that this doesn't required the html attribute of longDescription, that any method for conveying an extended description applies here be that a link to the description, aria-describedby, summary/details etc.

**Comment by madeleinerothberg** [comment]
Agree.
