### ISSUE TITLE
EPUB example needed accessibilityHazard

### ISSUE THREAD

**Issue by clapierre** [w3c/a11y-discov-vocab#18]
Should also include EPUB example
```
<package …>
   <metadata>
      …
      <meta
          property="schema:accessibilityHazard">
         flashingHazard
      </meta>
      <meta
          property="schema:accessibilityHazard">
         noMotionSimulationHazard
      </meta>
      <meta
          property="schema:accessibilityHazard">
         noSoundHazard
      </meta>
     	…
   </metadata>
   …
</package>
```

Should we also include the "none" case which would be the most common?

**Comment by mattgarrish** [comment]
I tried to limit each property to two examples and mix them up so we don't overrepresent any one way.

If we try to cover everything, we have to have json-ld, html+rdfa, html+microdata, and epub 3.

I'm sure we could script an option to change the examples so only one kind is showing, but it'll take some work to pull off within respec.

What about swapping "none" into the Holt textbook example for now?

**Comment by clapierre** [comment]
So replace the "noFlashingHazard", "noSoundHazard", and "noMotionSimulationHazard" with "none". I am fine with that.

**Comment by mattgarrish** [comment]
> So replace the "noFlashingHazard", "noSoundHazard", and "noMotionSimulationHazard" with "none".

Yes, I've fixed this in https://github.com/w3c/a11y-discov-vocab/commit/446abdf7de12e1f0c61db7882be12b2a71229179

I'll leave the issue open to consider what to do about covering all example cases, though.
