### ISSUE TITLE
Screen Reader Friendly

### ISSUE THREAD

**Issue by clapierre** [w3c/a11y-discov-vocab#19]
8. The accessModeSufficient property
8.1 Application

I think we should include what we have stated in our [User Experience Guide](https://www.w3.org/publishing/a11y/UX-Guide-metadata/techniques/epub-metadata/index.html#screen-reader-friendly) here as well for accessModeSufficient of textual.

From our document:
If this metadata exists (ie. textual within accessModeSufficient by itself) then report Screen Reader Friendly: Yes

Important: This is not the same as visual, textual or textual, visual because the combination means that the book requires both visual and textual abilities to access the data, not textual alone. Only having accessModeSufficient be textual as a separate entry ensures the document is screen reader friendly.

**Comment by madeleinerothberg** [comment]
Yes -- we'll need to expand a bit to compare single-value accessModeSufficient entries to multiple-value accessModeSufficient entries, since here it won't be in the context of Screen Reader Friendly, but I think it would be useful since this tends to be the hardest property to explain.
