### ISSUE TITLE
Extending accessibilityFeature for word dividers in Japanese publications

### ISSUE THREAD

**Issue by murata2makoto** [w3c/a11y-discov-vocab#2]
The Japan DAISY Consortium proposes to add two values for the use or non-use of space as word dividers in Japanese text.  Either or both of these values may be specified for a given EPUB publication. 　

Although this proposal is dated in 2021 March, we hope to make more experiments before we finalize these values.  I explained this idea to CLREQ people.

### 1) wordDividers/display

A Japanese EPUB publication containing this value can be rendered with space as word dividers _as explicitly specified by its author_.

`<meta property="schema:accessibilityFeature">wordDividers/display</meta>`

### 2) wordDivider/non-display

A Japanese EPUB publication containing this value can be rendered without space as word dividers.

`<meta property="schema:accessibilityFeature">wordDividers/non-display</meta>`

For more background information, see [Discovery of Space as Word Dividers](https://1drv.ms/w/s!An5Z79wj5AZBgt0Viic8ZsFZCzYLKQ?e=mS91tc).

**Comment by murata2makoto** [comment]
JDC changed its mind.  We propose to introduce two values.  

4.2.X.3 withAdditionalWordSegmentation

Indicates that the content can be rendered with additional word segmentation such as Japanese wakati-gaki and Thai word segmentation.

4.2.X.4 withoutAdditionalWordSegmentation

Indicates that the content can be rendered without additional word segmentation such as Japanese wakati-gaki and Thai word segmentation.

I will create a pull request about this.

**Comment by mattgarrish** [comment]
Closing with #79
