### ISSUE TITLE
Add previous version link

### ISSUE THREAD

**Issue by mattgarrish** [w3c/a11y-discov-vocab#41]
Trying to find out when the tableOfContents value got misplaced made me wish it was possible to view old versions of the vocabulary. I had to go to the wayback machine before discovering it was missing from the wiki.

Propose we manually add a "previous version" link and keep a dated copy of each release. It only adds one simple extra step to the release process (i.e., to copy the dated file that respec generates and then replace the index.html file in /latest).

**Comment by madeleinerothberg** [comment]
+1
