### ISSUE TITLE
Missing "IMS" in one instance

### ISSUE THREAD

**Issue by madeleinerothberg** [w3c/a11y-discov-vocab#43]
<Many of these properties were derived directly from the [Global Access for All (AfA) Information Model Data Element Specification ](http://www.imsglobal.org/accessibility/afav3p0pd/AfA3p0_DESinfoModel_v1p0pd.html). >

Is missing IMS in the link. Should be: 

<Many of these properties were derived directly from the [IMS Global Access for All (AfA) Information Model Data Element Specification ](http://www.imsglobal.org/accessibility/afav3p0pd/AfA3p0_DESinfoModel_v1p0pd.html).>

**Comment by mattgarrish** [comment]
I've fixed this in https://github.com/w3c/a11y-discov-vocab/commit/c8019e3e951f96325b7394e44e4f55c6e769e623

I also changed "Access for All" to "AccessForAll" to match the trademarked name.
