### ISSUE TITLE
Can you share anything with us at Schema.org about the usage of this markup?

### ISSUE THREAD

**Issue by danbri** [w3c/a11y-discov-vocab#54]
Hi from Schema.org!

It is great to see all the work on this recently.

We would love to know more about how this markup is being used, or efforts to use it, i.e. in data-consuming applications, as well as by publishers, content producers etc. Also any other specs (epub?) that reference it. Thanks for any pointers!

**Comment by iherman** [comment]
It is an integral part, so to say, of the EPUB 3.3 A11y spec:

- https://www.w3.org/TR/epub-a11y-11/
- https://www.w3.org/TR/epub-a11y-tech-11/

**Comment by mattgarrish** [comment]
Being a requirement of the accessibility specification we're starting to see it in more and more publications.

Publishers that are part of Benetech's [Global Certified Accessible program](https://bornaccessible.benetech.org/global-certified-accessible/), for example, are all producing the metadata in their content. There's a growing list here: https://bornaccessible.benetech.org/certified-publishers/

The metadata is also being implemented in the Italian publishing supply chain via Fondazione LIA.

We have verification of the metadata for EPUBs implemented in the [Ace validator](https://inclusivepublishing.org/toolbox/accessibility-checker/). It's also possible for publishers to review and edit metadata using the [Ace SMART tool](https://smart.daisy.org/).

Vendors and reading systems are also beginning to use the metadata. You can read about VitalSource's use of the metadata here: https://get.vitalsource.com/blog/the-next-step-in-accessibility-transparency

Thorium Reader also exposes accessibility metadata.

We also have [guides](https://www.w3.org/publishing/a11y/UX-Guide-metadata/techniques/epub-metadata/) explaining how to expose this information in a standardized way (continuing to be developed) as look to get this rolled out in more reading systems and bookstores.

We've also done work to integrate this metadata with the ONIX metadata format for trade publishing as another route to getting the information into supply chains. There is a crosswalk we host here: https://w3c.github.io/a11y-discov-vocab/crosswalk/

There's also work now on adapting the metadata for MARC records for use with library systems. A task force is currently [working on the mappings](https://w3c.github.io/publ-a11y/drafts/a11y-crosswalk-MARC/).

It's become pretty entwined in the epub ecosystem, in other words. @GeorgeKerscher @avneeshsingh @clapierre @gregoriopellegrino can probably fill in any gaps I'm missing.

Outside of EPUB I'm not sure how much uptake there's been. The metadata was originally designed as a complement to the LRMI metadata that was added to schema.org, but I'm not involved in that community. I would hope that if there's been uptake of LRMI for online resources that are not EPUBs, there's also been uptake of the accessibility metadata, but I can't speak to that.

We did get the WCAG group to acknowledge the potential usefulness of this metadata for accessibility report in the 2.1 release. It had to be done in a generic way, though, so it's probably not immediately recognizable, but this bullet in the [optional conformance reporting section](https://www.w3.org/TR/WCAG21/#conformance-optional) is a nod to the schema.org metadata:

> A list of specific accessibility characteristics of the content, provided in machine-readable metadata.

@madeleinerothberg might know if there's been uptake of the metadata elsewhere.

Anyway, that's everything that jumps to my mind quickly on a Friday afternoon... 😄

**Comment by clapierre** [comment]
The VitalSource Bookstore is now exposing this [metadata based on the guidelines we provided ](https://www.w3.org/publishing/a11y/UX-Guide-metadata/techniques/epub-metadata/)

Benetech has our own Bookstore which contains all our Global Certified Accessible books publishers submit to VitalSource and [you can see here one such accessible title](https://benetechaccessiblebooks.vitalsource.com/products/college-physics-roger-freedman-todd-ruskell-v9781319339180), if you click on the Accessibility Tab  and click the link View All Accessibility Metadata all this schema.org metadata exposed to the user.

The next step will be to recommend how to "discover" these accessible books with advance search options.  Displaying this metadata and ability to search this metadata is also on the Bookshare roadmap here at Benetech.

**Comment by mattgarrish** [comment]
Forgot to mention it's also integral to the W3C [Publication Manifest](https://www.w3.org/TR/pub-manifest/#accessibility) specification and, by extension, the [Audiobooks](https://www.w3.org/TR/audiobooks/) specification.

**Comment by Seirdy** [comment]
> We would love to know more about how this markup is being used, or efforts to use it…by publishers, content producers etc.

Do independent blogs count? I know I'm not a major publisher, but I think my approach could be a good reference for other authors.

Not many websites containing pictures-with-text (comics, memes, screenshots) include transcripts, so I think their presence should be announced. Some of my posts contain transcripts.

[This is an example of a post with two transcribed images](https://seirdy.one/posts/2020/11/23/website-best-practices/) ([section link to the first example](https://seirdy.one/posts/2020/11/23/website-best-practices/#xkcd-1309)).  The xkcd comic, caption, and transcript are all part of a section with the `VisualArtwork` and `ImageObject` types; the transcript is semantically linked to the image using `aria-describedby`. I decided to give the transcript the schema.org property of `embeddedTextCaption`, the figcaption a property of `caption`, the image src itself the properties of `image` and `contentUrl`, and the canonical xkcd permalink the property of `url`. Upon learning about the a11y discovery vocabulary, I also added the `transcript` accessibility feature.

Simplified markup:

``` html
<section itemprop="mentions" itemscope="" itemtype="https://schema.org/VisualArtwork https://schema.org/ImageObject" id="xkcd-1309">
  <h4 itemprop="name" id="infinite-scrolling">xkcd comic: infinite scrolling</h4>
  <figure>
    <img width="249" height="348" src="SRC" alt="Comic: infinite-scrolling books need careful handling to avoid losing the page." aria-describedby="transcript-xkcd-1309" itemprop="image contentUrl" />
    <figcaption itemprop="caption">
      <p>Infinite-scroll means that accidental navigation to a link results in losing your place. From <a itemprop="url" href="https://xkcd.com/1309/">xkcd</a></p>
    </figcaption>
  </figure>
  <details>
    <summary>Toggle comic <span itemprop="accessibilityFeature">transcript</span></summary>
    <section id="transcript-xkcd-1309">
      <h5>Comic transcript</h5>
      <div itemprop="embeddedTextCaption">
        <p>Megan stands at a desk, touching a book gingerly. Cueball stands behind her.</p>
        <dl>
          <dt>Cueball</dt>
          <dd>Why are you turning the pages like that?</dd>
          <dt>Megan</dt>
          <dd>If I touch the wrong thing, I’ll lose my place and have to start over.</dd>
          <dt>Caption below the panel</dt>
          <dd>If books worked like infinite-scrolling webpages</dd>
        </dl>
      </div>
    </section>
  </details>
</section>
```

The equivalent JSON-LD (generated from the microdata using Extruct):

``` json
{
  "@context": "http://schema.org",
  "@type": [
    "https://schema.org/VisualArtwork",
    "https://schema.org/ImageObject"
  ],
  "accessibilityFeature": "transcript",
  "caption": "Infinite-scroll means that accidental navigation to a link results in losing your place. From xkcd",
  "contentUrl": "SRC",
  "embeddedTextCaption": "Megan stands at a desk, touching a book gingerly. Cueball stands behind her.\n\nCueball\nWhy are you turning the pages like that?\nMegan\nIf I touch the wrong thing, I’ll lose my place and have to start over.\nCaption below the panel\nIf books worked like infinite-scrolling webpages",
  "image": "SRC",
  "name": "xkcd comic: infinite scrolling",
  "url": "https://xkcd.com/1309/"
}
```

On one hand, I do like a standard way to indicate the presence of a transcript in a part of a document. On the other hand, using it has led me to wonder if a property like `embeddedTextCaption` could make it a bit redundant. If structured data actually includes the transcribed text, then announcing its presence with a separate property isn't really necessary.
