### ISSUE TITLE
New version  "ONIX for Books codelists Issue 62"

### ISSUE THREAD

**Issue by ManfredMuchenberger** [w3c/a11y-discov-vocab#95]
Hi all

I am not a metadata specialist.

But we just had a discussion in a group of publishers about accessibility metadata and where wondering, if the a11y-discov-vocab group is aware that editeur recently released a new version of the ONIX for Books codelists. In the new Issue 62 many improvements to accommodate accessibility information have been incorporated.

We think it would be very important to also update the great “Schema.org Accessibility Properties Crosswalk” document.
https://w3c.github.io/a11y-discov-vocab/crosswalk/

This is a link to the new ONIX for Books codelists:
https://www.editeur.org/files/ONIX%20for%20books%20-%20code%20lists/ONIX_BookProduct_Codelists_Issue_62_Changes.pdf

Best regards
Manfred

-- 

Manfred Muchenberger
Head of Production

Swiss Library for the Blind, 
Visually Impaired and Print Disabled

**Comment by mattgarrish** [comment]
Hi @ManfredMuchenberger. Yes, we're aware of the updated code list. Editeur also did some work on a revised crosswalk.

@madeleinerothberg and @clapierre have you had a chance to look at the excel doc that was sent around? I assume we could use that to update the page once it's ready.

**Comment by clapierre** [comment]
I just added a PR #96 to handle the updated ONIX codes for ConformsTo.
There are still other new ONIX codes we should handle.
@gregoriopellegrino Do you agree with the following additions below?

accessibilityFeature: 
ARIA (196:30)
displayTransformability (196:36)
highContrastDisplay (196:37)
latex (196:35)
unknown (196:08)
Did I miss any?

We need to also remove section accessibilityAPI (as we have removed this)

 We also need to address the EAA exceptions:
75 EAA exception 1 – Micro-enterprises
76 EAA exception 2 – Disproportionate burden
77 EAA exception 3 – Fundamental modification

What were we thinking on how to handle this @mattgarrish?

**Comment by mattgarrish** [comment]
> What were we thinking on how to handle this @mattgarrish?

I would assume that you'd add these to the epub section of the crosswalk, like this:

| epub | onix |
| ----- | ----- |
| a11y:exemption with the value "micro-enterprise" | Code 75: EAA exception 1 - Micro-enterprises |

**Comment by mattgarrish** [comment]
Is the crosswalk ready to be republished yet, @clapierre ?

**Comment by mattgarrish** [comment]
Okay, cool. I've opened a request to republish in https://github.com/w3c/cg-reports/pull/37

Feel free to close this issue.

**Comment by clapierre** [comment]
Work done and requested to publish!
Thanks Matt

**Comment by ManfredMuchenberger** [comment]
Grat - thank you all for the great work! I am sure this will be very helpfull in the near future.
