### ISSUE TITLE
Add new Section for EAA Exceptions

### ISSUE THREAD

**Issue by clapierre** [w3c/a11y-discov-vocab#99]
We need a new section for EAA Exceptions.

75 EAA exception 1 – Micro-enterprises
76 EAA exception 2 – Disproportionate burden
77 EAA exception 3 – Fundamental modification

@mattgarrish you recommended

| epub | onix |
| ----- | ----- |
| a11y:exemption with the value "microenterprise" | Code 75: EAA exception 1 - Micro-enterprises |

Where should this go in our current document?

Would it go under 1. EPUB and ONIX

Or a new section 3. EAA Exceptions ?

**Comment by clapierre** [comment]
@gregoriopellegrino @mattgarrish Where do you all think this should go?  New section at the end similar to 1. EPUB and ONIX or at the end of section 1?

**Comment by gregoriopellegrino** [comment]
I think it should be in "EPUB and ONIX" section
